service: kezzle

plugins:
  - serverless-apigw-binary
  - serverless-plugin-typescript
  - serverless-offline

custom:
  apigwBinary:
    types:
      - '*/*'

provider:
  name: aws
  region: ap-northeast-2
  stage: dev
  runtime: nodejs18.x

functions:
  main:
    handler: src/lambda.handler
    events:
      - http:
          method: any
          path: /{any+}
          cors: true
